/// Flutter icons PrimoCons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
///
/// 
///
import 'package:flutter/widgets.dart';

class PrimoCons {
  PrimoCons._();

  static const _kFontFam = 'PrimoCons';
  static const String _kFontPkg = null;

  static const IconData finish = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconsett = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData powercells = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData controlpanel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData endgame = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
